@startuml 상품 이미지 맵핑 자동화
skinparam defaultFontName D2Coding

scale 2
title 상품 이미지 맵핑 자동화

participant EventBridge<<CatalogYo>>
participant Batch<<CatalogYo>>
participant SFTP<<중개사>>
participant FileCloud<<Yogiyo>>
database DB<<CatalogYo>>

EventBridge -> Batch : 정의된 스케줄 실행
activate Batch

Batch -> SFTP : CSV File Download\n(Include image URL)
activate SFTP

SFTP --> Batch
deactivate SFTP

loop 10 items
    Batch -> Batch : Image Download
    activate Batch

    Batch -> FileCloud : Image Upload
    activate FileCloud

    FileCloud --> Batch : response Filecloud URL
    deactivate FileCloud
    deactivate Batch
end

Batch -> DB : sync template
activate DB

DB --> Batch
deactivate DB


Batch -> EventBridge : 스케줄 종료
deactivate Batch


@enduml