@startuml 재고 저장 sequence diagram 
skinparam defaultFontName D2Coding

scale 2
title 재고 저장 sequence diagram 

participant 중개사<<beyond>>
participant Front<<CatalogYo>>
database DB<<CatalogYo>>

중개사 -> Front : request API \n30개 매장씩 나누어 호출
activate Front

Front -> DB : Bulk Update
activate DB

DB --> Front
deactivate DB


Front --> 중개사
deactivate Front


@enduml