@startuml 재고 저장 sequence diagram 
skinparam defaultFontName D2Coding

scale 2
title 재고 저장 sequence diagram 

participant 중개사<<beyond>>
participant Front<<CatalogYo>>
participant S3<<CatalogYo>>
participant Batch<<CatalogYo>>
database DB<<CatalogYo>>

중개사 -> Front : request API \nmultipart/form-data (.gz)
activate Front

alt 업데이트 재고 저장

    Front -> DB : Bulk Update
    activate DB

    DB --> Front
    deactivate DB
    
else 전체 재고 저장
    Front -> S3 : upload (.gz)
    activate S3

    S3 --> Front
    deactivate S3

    Front -> Batch : 배치 스케줄 실행
    activate Batch 

    Batch -> DB : Bulk Update
    activate DB

    DB --> Batch
    deactivate DB
    deactivate Batch


end

    Front --> 중개사
    deactivate Front


@enduml